steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/guruforu-web:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/guruforu-web:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/guruforu-web:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/guruforu-web:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'guruforu-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/guruforu-web:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/guruforu-web:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/guruforu-web:latest'

options:
  machineType: 'E2_HIGHCPU_2'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

